name: Run npm run build and npm test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2.5.1
     
    - run: npm install
    - run: npm run build --if-present
    - run: npm test --if-present
